server:
  port: 8081
spring:
  application:
    name: cloud-order-service

eureka:
  instance:
    hostname: localhost
    port: 7001
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    #是否从eurekaServer抓取自己的注册信息，默认是true。
    #单节点无所谓，集群必须设置为true擦能配个ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.FeignPaymentService: debug