server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名

  cloud:
    config:
      server:
        git:
          uri: https://github.com/july1992/Collect-config.git #GitHub上面的git仓库名字
#          uri: git@github.com:Giousa/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
#          username: july1992
#          passphrase: jhaku114
          search-paths:
#            - springcloud-config
            - config
      ####读取分支
      label: main
#  http://cloud-config-center:3344/main/config/config-dev
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#rabbitmq相关配置,暴露bus刷新配置的端点
#bus-refresh 是和里面默认配置相关
#management:
#  endpoints: #暴露bus刷新配置的端点
#    web:
#      exposure:
#        include: 'bus-refresh'


